# https://taskfile.dev

version: '3'
env:
  HOST_PROJECT_PATH: |
    {{- .HOST_PROJECT_PATH | default .PWD -}}
  HOST_HOME_PATH: |
    {{- .HOST_HOME_PATH | default .HOME -}}

tasks:
  install:
    desc: install
    silent: true
    run: when_changed
    sources:
      - '{{.HOST_PWD}}/services/**/*'
    cmds:
      - |
        yarn install
  start:
    desc: starts and push event.
    silent: true
    run: when_changed
    sources:
      - '{{.HOST_PWD}}/services/**/*'
    env:
      PORT: 3001
      PG_USER: '{{.PG_USER}}'
      PG_PASSWORD: '{{.PG_PASSWORD}}'
      PG_HOST: '{{.PG_HOST }}'
      PG_DB_NAME: '{{.PG_DB_NAME }}'
    cmds:
      - |
        yarn start:server
  send-events:
    desc: send events
    silent: true
    run: when_changed
    sources:
      - '{{.HOST_PWD}}/services/**/*'
    cmds:
      - |
        node utils/send-events.js
  docker-publish:
    desc: docker publish
    silent: true
    cmds:
      - |
        cd services/balance-event-api
        docker build -t gcr.io/customer-balance-420809/customer-balance .
        docker push gcr.io/customer-balance-420809/customer-balance
  deploy:
    desc: deploy
    silent: true
    cmds:
      - |
        cd terraform
        terraform init
        terraform plan -var-file="secrets.tfvars"  -out="out.plan"
        terraform apply "out.plan"
